#!/usr/bin/env bats
# Tests for scripts/sync-platforms.sh
#
# Each test runs the generator against a temporary copy of workflows/ and
# verifies that outputs land in the right places with the right shape.

setup() {
    ROOT="$(cd "$BATS_TEST_DIRNAME/.." && pwd)"
    WORK=$(mktemp -d)

    # Simulate a TARGET-style layout (post-install): workflows/ at the repo root,
    # outputs at .claude/, .agent/, .github/ (without the template/ prefix).
    # This exercises the target-mode branch of sync-platforms.sh.
    cp -R "$ROOT/template/workflows"  "$WORK/workflows"
    cp -R "$ROOT/scripts"             "$WORK/scripts"
    mkdir -p \
        "$WORK/.claude/commands/opsx" \
        "$WORK/.claude/skills" \
        "$WORK/.agent/skills" \
        "$WORK/.agent/workflows" \
        "$WORK/.github/skills" \
        "$WORK/.github/prompts"
}

teardown() {
    rm -rf "$WORK"
}

@test "generator exits 0 on happy path" {
    cd "$WORK"
    run bash scripts/sync-platforms.sh
    [ "$status" -eq 0 ]
    [[ "$output" == *"openspec-propose"* ]]
    [[ "$output" == *"openspec-apply-change"* ]]
    [[ "$output" == *"openspec-archive-change"* ]]
    [[ "$output" == *"openspec-explore"* ]]
}

@test "all three skill copies are byte-identical per workflow" {
    cd "$WORK"
    bash scripts/sync-platforms.sh

    for name in openspec-propose openspec-apply-change openspec-archive-change openspec-explore; do
        a="$(shasum -a 256 .claude/skills/$name/SKILL.md  | awk '{print $1}')"
        b="$(shasum -a 256 .agent/skills/$name/SKILL.md   | awk '{print $1}')"
        c="$(shasum -a 256 .github/skills/$name/SKILL.md  | awk '{print $1}')"
        [ "$a" = "$b" ]
        [ "$b" = "$c" ]
    done
}

@test "both workflow-format copies are byte-identical per workflow" {
    cd "$WORK"
    bash scripts/sync-platforms.sh

    for short in propose apply archive explore; do
        a="$(shasum -a 256 .agent/workflows/opsx-$short.md        | awk '{print $1}')"
        b="$(shasum -a 256 .github/prompts/opsx-$short.prompt.md  | awk '{print $1}')"
        [ "$a" = "$b" ]
    done
}

@test "generator is idempotent" {
    cd "$WORK"
    bash scripts/sync-platforms.sh
    BEFORE=$(find .claude/skills .agent .github .claude/commands -type f -exec shasum -a 256 {} + | sort)
    bash scripts/sync-platforms.sh
    AFTER=$(find .claude/skills .agent .github .claude/commands -type f -exec shasum -a 256 {} + | sort)
    [ "$BEFORE" = "$AFTER" ]
}

@test "GENERATED marker is placed after frontmatter, not before" {
    cd "$WORK"
    bash scripts/sync-platforms.sh

    for f in \
        .claude/skills/openspec-propose/SKILL.md \
        .claude/commands/opsx/propose.md \
        .agent/workflows/opsx-propose.md \
    ; do
        run head -1 "$f"
        [ "$output" = "---" ]  # frontmatter must open the file
    done
}

@test "GENERATED marker contains the canonical source path" {
    cd "$WORK"
    bash scripts/sync-platforms.sh

    run grep -l "GENERATED by scripts/sync-platforms.sh" \
        .claude/commands/opsx/propose.md \
        .claude/skills/openspec-propose/SKILL.md \
        .agent/workflows/opsx-propose.md
    [ "$status" -eq 0 ]
}

@test "description field is non-empty for each generated file" {
    cd "$WORK"
    bash scripts/sync-platforms.sh

    for f in .claude/skills/openspec-*/SKILL.md .agent/workflows/opsx-*.md .claude/commands/opsx/*.md; do
        run awk '/^description:/ { sub(/^description:[[:space:]]*/, ""); print; exit }' "$f"
        [ -n "$output" ]
    done
}

@test "command files use 'OPSX: Title' name format" {
    cd "$WORK"
    bash scripts/sync-platforms.sh

    run grep -l '^name: "OPSX: Propose"'  .claude/commands/opsx/propose.md
    [ "$status" -eq 0 ]
    run grep -l '^name: "OPSX: Apply"'    .claude/commands/opsx/apply.md
    [ "$status" -eq 0 ]
    run grep -l '^name: "OPSX: Archive"'  .claude/commands/opsx/archive.md
    [ "$status" -eq 0 ]
    run grep -l '^name: "OPSX: Explore"'  .claude/commands/opsx/explore.md
    [ "$status" -eq 0 ]
}

@test "old stale files are cleaned up before regeneration" {
    cd "$WORK"
    # Plant a stale file that should be wiped
    mkdir -p .claude/skills/openspec-stale
    echo "stale" > .claude/skills/openspec-stale/SKILL.md

    bash scripts/sync-platforms.sh

    [ ! -f .claude/skills/openspec-stale/SKILL.md ]
}
