#!/usr/bin/env bash
# sync-platforms.sh — Regenerate platform-specific workflow files from the
# canonical source in workflows/. Run this whenever workflows/ changes.
#
# Source of truth:
#   workflows/<skill-name>/SKILL.md   (SKILL.md format with full frontmatter)
#
# Generated outputs (DO NOT edit by hand):
#   .claude/skills/<skill-name>/SKILL.md            (identical copy)
#   .agent/skills/<skill-name>/SKILL.md             (identical copy)
#   .github/skills/<skill-name>/SKILL.md            (identical copy)
#   .agent/workflows/opsx-<short>.md                (workflow-format wrapper)
#   .github/prompts/opsx-<short>.prompt.md          (workflow-format wrapper)
#   .claude/commands/opsx/<short>.md                (command-format wrapper)
#
# Name mapping (canonical → slash-command short name):
#   openspec-propose         → propose
#   openspec-apply-change    → apply
#   openspec-archive-change  → archive
#   openspec-explore         → explore

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# Context detection:
#   - Kit repo (ask-ranger dev): canonical source lives at template/workflows/
#     and generated outputs go under template/.claude, template/.agent, template/.github.
#   - Target repo (after setup.sh installed): canonical source lives at workflows/
#     and generated outputs go at .claude/, .agent/, .github/ (repo root).
if [ -d "template/workflows" ]; then
    SRC_DIR="template/workflows"
    OUT_PREFIX="template/"
else
    SRC_DIR="workflows"
    OUT_PREFIX=""
fi

# Marker inserted after the closing frontmatter `---` so skill loaders do not
# mistake it for the description field.
gen_marker() {
    echo "<!-- GENERATED by scripts/sync-platforms.sh from ${SRC_DIR}/$1/SKILL.md — DO NOT EDIT -->"
}

# insert_marker_after_frontmatter <file> <marker>
# Emits the file with <marker> inserted on a new line immediately after the
# closing `---` of the YAML frontmatter. If no frontmatter exists, the marker
# is prepended.
insert_marker_after_frontmatter() {
    local file="$1" marker="$2"
    awk -v marker="$marker" '
        BEGIN { fm = 0; inserted = 0 }
        NR == 1 && /^---[[:space:]]*$/ { print; fm = 1; next }
        fm == 1 && /^---[[:space:]]*$/ { print; print marker; fm = 2; inserted = 1; next }
        { print }
        END {
            if (inserted == 0) {
                print "" > "/dev/stderr"
                print "[WARN] No frontmatter found in " FILENAME " — marker prepended" > "/dev/stderr"
            }
        }
    ' "$file"
}

# Name mappings: "<skill-name>|<short>|<command-title>"
MAPPINGS=(
    "openspec-propose|propose|OPSX: Propose"
    "openspec-apply-change|apply|OPSX: Apply"
    "openspec-archive-change|archive|OPSX: Archive"
    "openspec-explore|explore|OPSX: Explore"
)

# strip_frontmatter <file>
# Reads a file and emits the body only (everything after the second `---` line).
strip_frontmatter() {
    awk '
        BEGIN { in_fm = 0; past_fm = 0 }
        /^---[[:space:]]*$/ {
            if (NR == 1)     { in_fm = 1; next }
            if (in_fm == 1)  { in_fm = 0; past_fm = 1; next }
        }
        past_fm == 1 { print }
    ' "$1"
}

# skill_description <file>
# Reads the description field from the frontmatter of a SKILL.md file.
skill_description() {
    awk '
        /^---[[:space:]]*$/ { fm_count++ ; next }
        fm_count == 1 && /^description:/ {
            sub(/^description:[[:space:]]*/, "")
            print
            exit
        }
    ' "$1"
}

# ──────────────────────────────────────────────────────────────────────────────
# Clean out old generated files to prevent stale entries surviving a rename.
# ──────────────────────────────────────────────────────────────────────────────
rm -rf \
    "${OUT_PREFIX}.claude/skills/openspec-"* \
    "${OUT_PREFIX}.agent/skills/openspec-"* \
    "${OUT_PREFIX}.github/skills/openspec-"*
rm -f \
    "${OUT_PREFIX}.agent/workflows/opsx-"*.md \
    "${OUT_PREFIX}.github/prompts/opsx-"*.prompt.md \
    "${OUT_PREFIX}.claude/commands/opsx/"*.md

mkdir -p \
    "${OUT_PREFIX}.claude/commands/opsx" \
    "${OUT_PREFIX}.agent/workflows" \
    "${OUT_PREFIX}.github/prompts"

# ──────────────────────────────────────────────────────────────────────────────
# Regenerate
# ──────────────────────────────────────────────────────────────────────────────
for entry in "${MAPPINGS[@]}"; do
    IFS='|' read -r skill_name short title <<< "$entry"
    src="$SRC_DIR/$skill_name/SKILL.md"

    if [ ! -f "$src" ]; then
        echo "[WARN] Missing canonical: $src — skipping"
        continue
    fi

    marker="$(gen_marker "$skill_name")"
    description="$(skill_description "$src")"
    body="$(strip_frontmatter "$src")"

    # 1. Skill locations — canonical content with marker inserted after frontmatter
    for target in "${OUT_PREFIX}.claude/skills/$skill_name" "${OUT_PREFIX}.agent/skills/$skill_name" "${OUT_PREFIX}.github/skills/$skill_name"; do
        mkdir -p "$target"
        insert_marker_after_frontmatter "$src" "$marker" > "$target/SKILL.md"
    done

    # 2. Workflow-format files — minimal frontmatter + body
    for target in "${OUT_PREFIX}.agent/workflows/opsx-$short.md" "${OUT_PREFIX}.github/prompts/opsx-$short.prompt.md"; do
        {
            echo "---"
            echo "description: $description"
            echo "---"
            echo "$marker"
            printf '%s' "$body"
        } > "$target"
    done

    # 3. Claude command format
    {
        echo "---"
        echo "name: \"$title\""
        echo "description: $description"
        echo "category: Workflow"
        echo "tags: [workflow, artifacts, experimental]"
        echo "---"
        echo "$marker"
        printf '%s' "$body"
    } > "${OUT_PREFIX}.claude/commands/opsx/$short.md"

    echo "[OK] regenerated $skill_name (/opsx:$short)"
done

echo ""
echo "Sync complete. Canonical source: $SRC_DIR/<name>/SKILL.md"
